@startuml

MJRefreshAutoFooter -up--|> MJRefreshFooter
MJRefreshBackFooter -up--|> MJRefreshFooter
MJRefreshFooter -up--|> MJRefreshComponent
MJRefreshHeader -up--|> MJRefreshComponent
MJRefreshAutoGifFooter -up--|> MJRefreshAutoStateFooter
MJRefreshAutoNormalFooter -up--|> MJRefreshAutoStateFooter
MJRefreshAutoStateFooter -up--|> MJRefreshAutoFooter
MJRefreshBackGifFooter -up--|> MJRefreshBackStateFooter
MJRefreshBackNormalFooter -up--|> MJRefreshBackStateFooter
MJRefreshBackStateFooter -up--|> MJRefreshBackFooter
MJRefreshGifHeader -up--|> MJRefreshStateHeader
MJRefreshNormalHeader -up--|> MJRefreshStateHeader
MJRefreshStateHeader -up--|> MJRefreshHeader
CAIHRefreshAutoFooter -up--|> CAIHRefreshFooter
CAIHRefreshBackFooter -up--|> CAIHRefreshFooter
CAIHRefreshComponent -up--|> MJRefreshComponent
CAIHRefreshFooter -up--|> CAIHRefreshComponent
CAIHRefreshHeader -up--|> CAIHRefreshComponent
CAIHRefreshAutoGifFooter -up--|> CAIHRefreshAutoStateFooter
CAIHRefreshAutoNormalFooter -up--|> CAIHRefreshAutoStateFooter
CAIHRefreshAutoStateFooter -up--|> CAIHRefreshAutoFooter
CAIHRefreshBackGifFooter -up--|> CAIHRefreshBackStateFooter
CAIHRefreshBackNormalFooter -up--|> CAIHRefreshBackStateFooter
CAIHRefreshBackStateFooter -up--|> CAIHRefreshBackFooter
CAIHRefreshGifHeader -up--|> CAIHRefreshStateHeader
CAIHRefreshNormalHeader -up--|> CAIHRefreshStateHeader
CAIHRefreshStateHeader -up--|> CAIHRefreshHeader
MJChiBaoZiFooter -up--|> MJRefreshAutoGifFooter
MJChiBaoZiHeader -up--|> MJRefreshGifHeader
MJDIYAutoFooter -up--|> MJRefreshAutoFooter
MJDIYBackFooter -up--|> MJRefreshBackFooter
MJDIYHeader -up--|> MJRefreshHeader
MJExampleViewController -up--|> UITableViewController
MJExampleWindow -up--|> UIWindow
MJNavigationController -up--|> UINavigationController
MJSingleViewController -up--|> UITableViewController
MJTempViewController -up--|> UIViewController
AppDelegate -up--|> UIResponder
CAIHCollectionViewController -up--|> UICollectionViewController
MJCollectionViewController -up--|> UICollectionViewController
MJTableViewController -up--|> UITableViewController
MJChiBaoZiFooter2 -up--|> MJRefreshBackGifFooter
MJTestViewController -up--|> UIViewController
MJWebViewViewController -up--|> UIViewController
MJRefreshExampleTests -up--|> XCTestCase


class MJRefreshAutoFooter
class MJRefreshFooter
class MJRefreshBackFooter
class MJRefreshComponent
class MJRefreshHeader
class MJRefreshAutoGifFooter
class MJRefreshAutoStateFooter
class MJRefreshAutoNormalFooter
class MJRefreshBackGifFooter
class MJRefreshBackStateFooter
class MJRefreshBackNormalFooter
class MJRefreshGifHeader
class MJRefreshStateHeader
class MJRefreshNormalHeader
class CAIHRefreshAutoFooter
class CAIHRefreshFooter
class CAIHRefreshBackFooter
class CAIHRefreshComponent
class CAIHRefreshHeader
class CAIHRefreshAutoGifFooter
class CAIHRefreshAutoStateFooter
class CAIHRefreshAutoNormalFooter
class CAIHRefreshBackGifFooter
class CAIHRefreshBackStateFooter
class CAIHRefreshBackNormalFooter
class CAIHRefreshGifHeader
class CAIHRefreshStateHeader
class CAIHRefreshNormalHeader
class MJChiBaoZiFooter
class MJChiBaoZiHeader
class MJDIYAutoFooter
class MJDIYBackFooter
class MJDIYHeader
class MJExampleViewController
class UITableViewController
class MJExampleWindow
class UIWindow
class MJNavigationController
class UINavigationController
class MJSingleViewController
class MJTempViewController
class UIViewController
class AppDelegate
class UIResponder
class CAIHCollectionViewController
class UICollectionViewController
class MJCollectionViewController
class MJTableViewController
class MJChiBaoZiFooter2
class MJTestViewController
class MJWebViewViewController
class MJRefreshExampleTests
class XCTestCase



@enduml
